# Generated by Django 4.2 on 2023-06-03 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=180)),
                ('avatar', models.ImageField(default='cliente/avatar_default.png', upload_to='cliente/')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='o cpf informado deverá esta no formato 999.999.999-99', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('type_cliente', models.CharField(choices=[('f', 'pessoa-fisica'), ('e', 'empresa')], default='f', help_text='tipo de cliente', max_length=1)),
            ],
        ),
    ]
