# Generated by Django 4.2 on 2023-06-08 17:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cliente', models.CharField(choices=[('pf', 'pessoa fisica'), ('em', 'empresa')], default='pf', max_length=2)),
                ('avatar', models.ImageField(default='cliente/avatar_default.png', upload_to='cliente/')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='o cpf informado deverá esta no formato 999.999.999-99', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cliente', models.CharField(choices=[('pf', 'pessoa fisica'), ('em', 'empresa')], default='pf', max_length=2)),
                ('logo', models.ImageField(default='cliente/avatar_default.png', upload_to='cliente/empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='o cnpj informado deverá esta no formato XX.XXX.XXX0001-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{7}\\-\\d{2}$')])),
                ('segmento', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
