# Generated by Django 4.2.2 on 2023-06-07 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(
                max_length=18,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="o cpf informado deverá esta no formato XX.XXX.XXX0001-XX",
                        regex="^\\d{2}\\.\\d{3}\\.\\d{7}\\-\\d{2}$",
                    )
                ],
            ),
        ),
    ]
