# Generated by Django 4.2 on 2023-06-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='type_cliente',
        ),
    ]
