# Generated by Django 4.2 on 2023-06-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='logo',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='avatar',
            new_name='img',
        ),
    ]
