# Generated by Django 4.2 on 2023-06-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_logo_empresa_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='total_compras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='total_gasto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
