# Generated by Django 4.2.1 on 2023-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_alter_cliente_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="avatar",
            field=models.ImageField(
                default="cliente/avatar_default.png", upload_to="cliente/"
            ),
        ),
    ]
