# Generated by Django 4.2.1 on 2023-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0004_cliente_type_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="password",
            field=models.CharField(default=None, max_length=8),
        ),
    ]
