# Generated by Django 4.2.2 on 2023-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0004_empresa_total_ganho_empresa_total_vendas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="total_ganho",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="total_vendas",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="total_compras",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="total_gasto",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
