# Generated by Django 4.2.1 on 2023-05-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0006_alter_cliente_password"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="password",),
    ]
