# Generated by Django 4.2.1 on 2023-06-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0008_cliente_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="user",),
    ]
