# Generated by Django 4.2.1 on 2023-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0012_remove_cliente_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="type_cliente",
            field=models.CharField(
                choices=[("f", "pessoa-fisica"), ("e", "empresa")],
                default="f",
                help_text="tipo de cliente",
                max_length=1,
            ),
        ),
    ]
