# Generated by Django 4.2.1 on 2023-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="fotos",
            field=models.ImageField(null=True, upload_to="produto/"),
        ),
    ]
