# Generated by Django 4.2.2 on 2023-06-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="produto", name="media_stars",),
    ]
