# Generated by Django 4.2.2 on 2023-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_remove_produto_media_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="media_stars",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
