# Generated by Django 4.2 on 2023-05-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_quantidade_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.categoria'),
        ),
    ]
