# Generated by Django 4.2 on 2023-05-20 16:12

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_remove_categoria_produto_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='produto/produto_default.png', upload_to=produto.models.caminho_personalizado),
        ),
    ]
