# Generated by Django 4.2 on 2023-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='produto/produto_default.png', upload_to='produto/'),
        ),
    ]
