# Generated by Django 4.2 on 2023-05-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('o', 'oferta'), ('f', 'falta'), ('n', 'normal')], default='n', help_text='status do produto', max_length=1),
        ),
    ]
