# Generated by Django 4.2 on 2023-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='nome',
            field=models.CharField(default='carrinho_default', max_length=200),
        ),
    ]
