# Generated by Django 4.2.2 on 2023-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrinho", "0003_alter_itemcarrinho_carrinho"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="preco_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="carrinho",
            name="qtd_produtos",
            field=models.IntegerField(default=0),
        ),
    ]
