# Generated by Django 4.2 on 2023-06-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_carrinho_preco_total_carrinho_qtd_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
