# Generated by Django 4.2 on 2023-06-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0006_itemcarrinho_preco_acumulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ss', 'sem status'), ('pp', 'pagamento pedente'), ('ec', 'produto à caminho'), ('se', 'saiu para entrega'), ('re', 'produto recebido')], default='ss', max_length=2)),
                ('data', models.DateField()),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho')),
            ],
        ),
    ]
