# Generated by Django 4.2.2 on 2023-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrinho", "0008_carrinho_close_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinho",
            name="nome",
            field=models.CharField(default="carrinho", max_length=200),
        ),
    ]
